version: "3.1"

services:
  mediaserver:
    build: ./server
    container_name: mediaserver
    ports:
      - 1935:1935
      - 1936:1936
      - 1937:1937
      - 8000:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - ./server:/usr/src/app

  haproxy:
    image: haproxy:lts-alpine
    container_name: haproxy
    ports:
      - 4321:4321
    volumes:
      - ./proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - mediaserver
